extends: airbnb-base
plugins:
  - import
rules:
  no-process-env: 2
  no-underscore-dangle: off
  no-async-promise-executor: off
globals:
  process: readonly
  describe: readonly
  before: readonly
  after: readonly
  beforeEach: readonly
  afterEach: readonly
  suite: readonly
  test: readonly
  it: readonly
  expect: readonly
